### PR TITLE
Test wrong version being reported

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Ah, sorry, I missed that you were testing here.

**Comment by xylar** [comment]
It this doesn't fail as expected, I'm happy to do another PR to fix #18

**Comment by xylar** [comment]
Hmm, it failed as it should but it doesn't give any useful info, which it a bit annoying.  Perhaps something to fix.

**Comment by jan-janssen** [comment]
All fine - your code is working as expected, I just mixed it up.

**Comment by xylar** [comment]
Great, no worries.  I'm glad we got it figured out!

**Pull request closed without merging**
